name: React-Native-Expo-Awesome-Template
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set Git User Identity
        run: |
          git config --global user.email "mehdi.abdollahi3578@gmail.com"
          git config --global user.name "ilz5753"
      - name: Bump version and create a release
        run: npm version patch -m "Bump version to %s"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}