name: NPM Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set Git User Identity
        run: |
          git config --global user.email "mehdi.abdollahi3578@gmail.com"
          git config --global user.name "ilz5753"

      - name: Install dependencies
        run: npm install

      - name: Bump version and create a release
        run: npm version patch -m "Bump version to %s"

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
